[package]
name = "database"
version = "0.1.0"
authors = ["benjamin <bbloot@dynasource.com>"]

[dependencies]
diesel = { version = "1.0.0", features = ["postgres"] }
r2d2 = "*"
rocket = "0.3.16"
r2d2-diesel = "1.0.0"
uuid = "0.7"
dotenv = "0.9.0"
dotenv_codegen = "0.11.0"
